version: "3.7"

services:

  invite_postgres:
    container_name: invite_postgres
    image: "postgres:13.4"
    env_file: .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "10001:5432"
    restart: always
    networks:
      - net

  invite_telegram:
    container_name: invite_tg
    depends_on:
      - invite_postgres
    build: ./bot
    env_file: .env
    command: python /code/bot/main.py
    volumes:
      - ./bot:/code/bot
    networks:
      - net

volumes:
  db_data:

networks:
  net:
    driver: bridge
